-- LTC Insurance Platform - Table Creation Script
-- Creates POLICY_MONTHLY_SNAPSHOT_FACT and CLAIMS_TPA_FEE_WORKSHEET_SNAPSHOT_FACT tables

-- Create database and schema (if not exists)
CREATE DATABASE IF NOT EXISTS LTC_INSURANCE;
USE DATABASE LTC_INSURANCE;

CREATE SCHEMA IF NOT EXISTS ANALYTICS;
USE SCHEMA ANALYTICS;

-- ============================================================================
-- POLICY_MONTHLY_SNAPSHOT_FACT Table
-- ============================================================================
CREATE OR REPLACE TABLE POLICY_MONTHLY_SNAPSHOT_FACT (
    POLICY_MONTHLY_SNAPSHOT_ID VARCHAR(36),
    POLICY_DIM_ID VARCHAR(36),
    POLICY_ID NUMBER(38,0),
    INSURED_LIFE_DIM_ID VARCHAR(36),
    INSURED_LIFE_ID NUMBER(38,0),
    INSURED_CITY VARCHAR(100),
    INSURED_STATE VARCHAR(12),
    INSURED_ZIP VARCHAR(10),
    POLICY_RESIDENCE_STATE VARCHAR(12),
    PAF_RELATIONSHIP_DIM_ID VARCHAR(32),
    MEMBER_LIFE_DIM_ID VARCHAR(32),
    MEMBER_LIFE_ID NUMBER(38,0),
    GRP_DIM_ID VARCHAR(36),
    ANNUALIZED_PREMIUM NUMBER(18,2),
    LIFETIME_COLLECTED_PREMIUM NUMBER(18,2),
    LIFETIME_WAIVER_PREMIUM NUMBER(18,2),
    PREMIUM_FREQUENCY VARCHAR(50),
    OFFSET_PREMIUM NUMBER(18,2),
    POLICY_STATUS_DIM_ID VARCHAR(36),
    CURRENT_COVERAGE_ID NUMBER(38,0),
    CURRENT_COVERAGE_DIM_ID VARCHAR(36),
    ORIGINAL_EFFECTIVE_DT_ID VARCHAR(36),
    ORIGINAL_EFFECTIVE_DT TIMESTAMP_NTZ(9),
    COVERAGE_EFFECTIVE_DT_ID VARCHAR(36),
    COVERAGE_EFFECTIVE_DT TIMESTAMP_NTZ(9),
    COVERAGE_STATUS_DT_ID VARCHAR(36),
    COVERAGE_STATUS_DT TIMESTAMP_NTZ(9),
    COVERAGE_EXPIRATION_DT_ID VARCHAR(36),
    COVERAGE_EXPIRATION_DT TIMESTAMP_NTZ(9),
    POLICY_EXPIRATION_DT_ID VARCHAR(36),
    POLICY_EXPIRATION_DT TIMESTAMP_NTZ(9),
    APPN_RCV_DT_ID VARCHAR(36),
    APPN_RCV_DT TIMESTAMP_NTZ(9),
    APPN_SIG_DT_ID VARCHAR(36),
    APPN_SIG_DT TIMESTAMP_NTZ(9),
    APPN_SIG_STATE VARCHAR(12),
    CURRENT_WAIVER_EFFECTIVE_DATE_ID VARCHAR(36),
    CURRENT_WAIVER_EFFECTIVE_DATE TIMESTAMP_NTZ(9),
    CURRENT_WAIVER_EXPIRATION_DATE_ID VARCHAR(36),
    CURRENT_WAIVER_EXPIRATION_DATE TIMESTAMP_NTZ(9),
    IN_WAIVER_FLG VARCHAR(3),
    IN_WAIVER_DESC VARCHAR(255),
    CURRENT_NONFORFEITURE_EFFECTIVE_DATE_ID VARCHAR(36),
    CURRENT_NONFORFEITURE_EFFECTIVE_DATE TIMESTAMP_NTZ(9),
    CURRENT_NONFORFEITURE_EXPIRATION_DATE_ID VARCHAR(36),
    CURRENT_NONFORFEITURE_EXPIRATION_DATE TIMESTAMP_NTZ(9),
    IN_NONFORFEITURE_FLG VARCHAR(3),
    IN_NONFORFEITURE_DESC VARCHAR(255),
    CURRENT_SURVIVORSHIP_EFFECTIVE_DATE_ID VARCHAR(36),
    CURRENT_SURVIVORSHIP_EFFECTIVE_DATE TIMESTAMP_NTZ(9),
    CURRENT_SURVIVORSHIP_EXPIRATION_DATE_ID VARCHAR(36),
    CURRENT_SURVIVORSHIP_EXPIRATION_DATE TIMESTAMP_NTZ(9),
    SURVIVORSHIP_FLG VARCHAR(3),
    SURVIVORSHIP_DESC VARCHAR(255),
    PAID_TO_DATE_ID VARCHAR(36),
    PAID_TO_DATE TIMESTAMP_NTZ(9),
    LATEST_CLAIM_DIM_ID VARCHAR(36),
    LATEST_CLAIM_ID NUMBER(38,0),
    RATED_AGE NUMBER(38,0),
    RATED_DATE TIMESTAMP_NTZ(9),
    TAX_QUALIFICATION_DIM_ID VARCHAR(50),
    BENEFIT_INFLATION VARCHAR(50),
    BENEFIT_INCREASE VARCHAR(50),
    FIRST_EOB_DECISION_DT TIMESTAMP_NTZ(9),
    FIRST_EOB_DECISION_DT_ID VARCHAR(36),
    LATEST_EOB_DECISION_DT TIMESTAMP_NTZ(9),
    LATEST_EOB_DECISION_DT_ID VARCHAR(36),
    LATEST_CLAIM_INCURRED_DT TIMESTAMP_NTZ(9),
    LATEST_CLAIM_INCURRED_DT_ID VARCHAR(36),
    LATEST_CLAIM_EXPIRATION_DT TIMESTAMP_NTZ(9),
    LATEST_CLAIM_EXPIRATION_DT_ID VARCHAR(36),
    CLAIM_STATUS_CD VARCHAR(50),
    CLAIMANT_SEX VARCHAR(12),
    CLAIM_PAID_DT TIMESTAMP_NTZ(9),
    CLAIM_PAID_DT_ID VARCHAR(36),
    TOTAL_REQUEST_FOR_REIMBURSMENT_BENEFIT NUMBER(18,2),
    TOTAL_REQUEST_FOR_REIMBURSMENT_ADMIN NUMBER(18,2),
    TOTAL_REQUEST_FOR_REIMBURSMENT_PENDING NUMBER(18,2),
    TOTAL_REQUEST_FOR_REIMBURSMENT_REQUESTED_AMOUNT NUMBER(18,2),
    TOTAL_REQUEST_FOR_REIMBURSMENT_UNPAID_AMOUNT NUMBER(18,2),
    DISABLING_EVENT_ICD_DIM_ID VARCHAR(36),
    PRIMARY_DIAGNOSIS_ICD_DIM_ID VARCHAR(36),
    TOTAL_ACTIVE_CLAIMS NUMBER(38,0),
    TOTAL_RFBS NUMBER(38,0),
    TOTAL_APPROVED_RFBS NUMBER(38,0),
    TOTAL_DENIALS NUMBER(38,0),
    CARRIER_NAME VARCHAR(150),
    ENVIRONMENT VARCHAR(10),
    POLICY_SNAPSHOT_DATE VARCHAR(36)
);

-- ============================================================================
-- CLAIMS_TPA_FEE_WORKSHEET_SNAPSHOT_FACT Table
-- ============================================================================
CREATE OR REPLACE TABLE CLAIMS_TPA_FEE_WORKSHEET_SNAPSHOT_FACT (
    TPA_FEE_WORKSHEET_SNAPSHOT_FACT_ID VARCHAR(32),
    POLICY_DIM_ID VARCHAR(32),
    CLAIMANTNAME VARCHAR(100),
    POLICY_NUMBER VARCHAR(20),
    DECISION VARCHAR(30),
    LATEST_EOB_START_DT DATE,
    LATEST_EOB_END_DT DATE,
    CERTIFICATIONDATE DATE,
    ONGOING_RATE_MONTH NUMBER(38,0),
    INITIAL_DECISIONS_FACILITIES NUMBER(38,0),
    INITIAL_DECISIONS_HOME_HEALTH NUMBER(38,0),
    INITIAL_DECISIONS_ALL_OTHER NUMBER(38,0),
    ONGOING_ALL_FACILITIES NUMBER(38,0),
    ONGOING_HOME_HEALTH NUMBER(38,0),
    ALL_OTHER NUMBER(38,0),
    RETRO_ALL_FACILITIES NUMBER(38,0),
    RETRO_HOME_HEALTH NUMBER(38,0),
    RETRO_ALL_OTHER NUMBER(38,0),
    RETRO_MONTHS NUMBER(38,0),
    RFB_ID NUMBER(38,0),
    RFB_ENTERED_DT DATE,
    RFB_CLAIM_FORM_RCPT_DT DATE,
    INITIAL_APPROVAL_DT DATE,
    RFB_INITIAL_INQUIRY_DT DATE,
    RFB_CLAIM_PACKET_SENT_DT DATE,
    RFB_STATISTICAL_START_DT DATE,
    RFB_STATISTICAL_END_DT DATE,
    RFB_PROCESS_TO_DECISION_TAT NUMBER(38,0),
    RFB_REFERENCE VARCHAR(50),
    INITIAL_TO_PACKET_TAT NUMBER(38,0),
    CLAIM_INCURRED_DT DATE,
    CLAIM_EXPIRATION_DT DATE,
    EPISODE_OF_BENEFIT_ID NUMBER(38,0),
    EB_CREATION_DT DATE,
    FIRSTEBDECISIONDT DATE,
    EB_REASSESSMENT_DT DATE,
    TOTAL_ELIGIBLE_PROVIDER_COUNT NUMBER(38,0),
    PENDING_PROVIDER_COUNT NUMBER(38,0),
    INELIGIBLE_PROVIDER_COUNT NUMBER(38,0),
    INFORMAL_PROVIDER_COUNT NUMBER(38,0),
    POC_PROVIDER_ID NUMBER(38,0),
    PPSD_START_DT DATE,
    PPSD_END_DT DATE,
    POC_PROVIDER_TYPE_DESC VARCHAR(50),
    EOB_CREATION_TO_DECISION_TAT NUMBER(38,0),
    LIFE_STATE VARCHAR(2),
    ISSUE_STATE VARCHAR(2),
    POLICY_RESIDENCE_STATE VARCHAR(2),
    SNAPSHOT_DATE DATE,
    LOAD_DATE TIMESTAMP_NTZ(3),
    CARRIER_NAME VARCHAR(100),
    CLAIM_TYPE_CD NUMBER(38,0),
    DECISION_EXCLUDING_PRE_AUTHORIZATION_FACILITY_ONLY NUMBER(38,0),
    DECISION_EXCLUDING_PRE_AUTHORIZATION_ALF NUMBER(38,0),
    DECISION_EXCLUDING_PRE_AUTHORIZATION_ALL_OTHER_POLICIES NUMBER(38,0),
    CLOSED_PRE_AUTHORIZATION_NO_DECISION NUMBER(38,0),
    CLOSED_PRE_AUTHORIZATION_APPROVAL NUMBER(38,0),
    CLOSED_PRE_AUTHORIZATION_DENIAL NUMBER(38,0),
    CO_MED_DIR_REVIEW_INITIAL NUMBER(38,0),
    CO_MED_DIR_REVIEW_APPEAL NUMBER(38,0),
    RESTORATION_OF_BENEFITS NUMBER(38,0),
    IS_INITIAL_DECISION_FLAG NUMBER(38,0)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_policy_id ON POLICY_MONTHLY_SNAPSHOT_FACT(POLICY_ID);
CREATE INDEX IF NOT EXISTS idx_policy_carrier ON POLICY_MONTHLY_SNAPSHOT_FACT(CARRIER_NAME);
CREATE INDEX IF NOT EXISTS idx_policy_snapshot_date ON POLICY_MONTHLY_SNAPSHOT_FACT(POLICY_SNAPSHOT_DATE);

CREATE INDEX IF NOT EXISTS idx_claims_id ON CLAIMS_TPA_FEE_WORKSHEET_SNAPSHOT_FACT(TPA_FEE_WORKSHEET_SNAPSHOT_FACT_ID);
CREATE INDEX IF NOT EXISTS idx_claims_carrier ON CLAIMS_TPA_FEE_WORKSHEET_SNAPSHOT_FACT(CARRIER_NAME);
CREATE INDEX IF NOT EXISTS idx_claims_snapshot_date ON CLAIMS_TPA_FEE_WORKSHEET_SNAPSHOT_FACT(SNAPSHOT_DATE);
CREATE INDEX IF NOT EXISTS idx_claims_decision ON CLAIMS_TPA_FEE_WORKSHEET_SNAPSHOT_FACT(DECISION);

-- Confirm tables created
SELECT 'Tables created successfully' AS status;

